# server
server:
  port: 5555

# eureka
eureka:
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
          defaultZone: http://localhost:8761/eureka

# endpoint de configuração do zuul
management:
  endpoints:
      web:
        exposure:
            include:
              - "routes"

zuul:
  sensitive-headers:
    - Cookie, Authorization