server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/hugows007/microservice.git
          search-paths:
          - microservice-repo/transportador
          - microservice-repo/loja
          - microservice-repo/fornecedor

